### ISSUE TITLE
Missing ez_setup requirement 

### ISSUE THREAD

**Issue by ilija139** [dme65/pySOT#4] opened 2016-01-26 08:44 UTC
The module ez_setup is also required (https://github.com/dme65/pySOT/blob/master/setup.py#L13)

**Comment by dme65** [comment] 2016-01-26 16:53
This is related to the inspyred dependency which comes from the pyKriging module. Marked as a duplicate of (https://github.com/dme65/pySOT/issues/5).

**Closed by dme65** 2016-01-26 16:53 UTC
